affinity: {}
autoscaling:
  enabled: false
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
fullnameOverride: ''
image:
  imageName: resourceservice
  pullPolicy: IfNotPresent
  repository: dockerhub.vertexwan.cn/pri/
  tag: 1.0.5
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
  className: ''
  enabled: false
  hosts:
  - host: test.org
    paths:
    - path: /
      pathType: Prefix
  tls: []
livenessProbe:
  failureThreshold: 300
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  tcpSocket:
    port: 9666
  timeoutSeconds: 5
nameOverride: ''
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
readinessProbe:
  failureThreshold: 100
  initialDelaySeconds: 20
  periodSeconds: 10
  successThreshold: 1
  tcpSocket:
    port: 9666
  timeoutSeconds: 1
replicaCount: 1
resources:
  limits:
    cpu: 0.5
    memory: 1Gi
securityContext: {}
service:
  port: 9666
  scrape:
    enable: true
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: true
  name: ''
tolerations: []
