apiVersion: v1
kind: Service
metadata:
  name: {{ include "resourceservice.fullname" . }}
  labels:
    {{- include "resourceservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "resourceservice.selectorLabels" . | nindent 4 }}
